language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
